// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace InternalMessaging.Core.Models
{
    public partial class Order
    {
        private string _bookedMechanicFullName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string BookedMechanicFullName
        {
            get { return this._bookedMechanicFullName; }
            set { this._bookedMechanicFullName = value; }
        }
        
        private string _bookedMechanicSignature;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string BookedMechanicSignature
        {
            get { return this._bookedMechanicSignature; }
            set { this._bookedMechanicSignature = value; }
        }
        
        private DateTimeOffset? _bookedTime;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? BookedTime
        {
            get { return this._bookedTime; }
            set { this._bookedTime = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private double? _estimate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Estimate
        {
            get { return this._estimate; }
            set { this._estimate = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _invoiceState;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string InvoiceState
        {
            get { return this._invoiceState; }
            set { this._invoiceState = value; }
        }
        
        private string _registrationNumber;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RegistrationNumber
        {
            get { return this._registrationNumber; }
            set { this._registrationNumber = value; }
        }
        
        private string _repairState;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RepairState
        {
            get { return this._repairState; }
            set { this._repairState = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Order class.
        /// </summary>
        public Order()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken bookedMechanicFullNameValue = inputObject["BookedMechanicFullName"];
                if (bookedMechanicFullNameValue != null && bookedMechanicFullNameValue.Type != JTokenType.Null)
                {
                    this.BookedMechanicFullName = ((string)bookedMechanicFullNameValue);
                }
                JToken bookedMechanicSignatureValue = inputObject["BookedMechanicSignature"];
                if (bookedMechanicSignatureValue != null && bookedMechanicSignatureValue.Type != JTokenType.Null)
                {
                    this.BookedMechanicSignature = ((string)bookedMechanicSignatureValue);
                }
                JToken bookedTimeValue = inputObject["BookedTime"];
                if (bookedTimeValue != null && bookedTimeValue.Type != JTokenType.Null)
                {
                    this.BookedTime = ((DateTimeOffset)bookedTimeValue);
                }
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken estimateValue = inputObject["Estimate"];
                if (estimateValue != null && estimateValue.Type != JTokenType.Null)
                {
                    this.Estimate = ((double)estimateValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken invoiceStateValue = inputObject["InvoiceState"];
                if (invoiceStateValue != null && invoiceStateValue.Type != JTokenType.Null)
                {
                    this.InvoiceState = ((string)invoiceStateValue);
                }
                JToken registrationNumberValue = inputObject["RegistrationNumber"];
                if (registrationNumberValue != null && registrationNumberValue.Type != JTokenType.Null)
                {
                    this.RegistrationNumber = ((string)registrationNumberValue);
                }
                JToken repairStateValue = inputObject["RepairState"];
                if (repairStateValue != null && repairStateValue.Type != JTokenType.Null)
                {
                    this.RepairState = ((string)repairStateValue);
                }
            }
        }
    }
}
