// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using InternalMessaging.Core;
using InternalMessaging.Core.Models;
using Microsoft.Rest;

namespace InternalMessaging.Core
{
    public static partial class VirtualAutoRepairExtensions
    {
        /// <param name='operations'>
        /// Reference to the InternalMessaging.Core.IVirtualAutoRepair.
        /// </param>
        public static IList<Order> GetAll(this IVirtualAutoRepair operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IVirtualAutoRepair)s).GetAllAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the InternalMessaging.Core.IVirtualAutoRepair.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Order>> GetAllAsync(this IVirtualAutoRepair operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<InternalMessaging.Core.Models.Order>> result = await operations.GetAllWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
